

class Listing {
    constructor(n, s, t, p, b, c, cond, charCount, tagCount) {

        //User Input via API call
        this.name = n;  //Product title
        this.size = s;  //Size
        this.type = t;  //Product category (shirt, pants, etc.)
        this.price = p; //Price
        this.brand = b; //Brand
        this.count = c; //Quantity in Stock
        this.condition = cond; //Used condition

        //Generated by methods
        this.desciption = this.generateDescrip(charCount);  //AI Generated Desciption
        this.tags = this.generateTags(tagCount); //AI Generated Hashtags
    }

    generateDescrip(charCount) {
        let d = "";

        //Use OPEN AI to generate
        return d;
    }

    generateTags(tagCount) {
        let t = [];

        //Use OPENAi to generate

        return t;
    }
}

class DePopListing extends Listing {
    constructor(n, s, t, p, d, b, c, cond, age) {
        super(n, s, t, p, d, b, c, cond);

        this.age = age; //Year Item was made
    }

    //Methods

}
class EbayListing extends Listing {
    constructor(n, s, t, p, d, b, c, cond, team, player, gender) {
        super(n, s, t, p, d, b, c, cond);

        this.team = team; //Team apperael
        this.player = player; //Player from team
        this.gender = gender  //Gender
    }

    //Methods

}
class GrailedListing extends Listing {
    constructor(n, s, t, p, d, b, c, cond, gender, fp) {
        super(n, s, t, p, d, b, c, cond);

        this.gender = gender  //Gender
        this.floorPrice = fp;
    }

    //Methods

}